[package]
name = "templating-yarte"
version = "1.0.0"
publish = false
edition = "2021"

[package.metadata.cargo-machete]
ignored = [
    "yarte_helpers" # only used as build dependency
]

[dependencies]
actix-web.workspace = true
derive_more.workspace = true
env_logger.workspace = true
log.workspace = true
yarte = { version = "0.15", features = ["bytes-buf", "html-min"] }

[build-dependencies]
yarte_helpers = { version = "0.15", default-features = false, features = ["config"] }
