name: trigger docs change webhook workflow

on: 
  workflow_dispatch:   

jobs:
  handle-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq
      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git                    
      - name: Trigger Target Workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TARGET_REPO_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/r-nacos/docs/actions/workflows/update_change_log.yaml/dispatches \
            -f "ref=master"             

