[package]
name = "shutdown-server"
version = "1.0.0"
edition = "2021"
description = "Send a request to the server to shut it down"

[dependencies]
actix-web.workspace = true
actix-web-lab.workspace = true

env_logger.workspace = true
log.workspace = true
parking_lot.workspace = true
