[package]
name = "my_rust_lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] # Crucial for creating a shared library Python can load

[dependencies]
pyo3 = { version = "0.22.2", features = ["extension-module"] }
