[package]
name = "templating-askama"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web.workspace = true
askama = "0.12"
env_logger.workspace = true
log.workspace = true

[build-dependencies]
askama = "0.12"
