[package]
name = "templating-fluent"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web.workspace = true
actix-web-lab.workspace = true
env_logger.workspace = true
fluent-templates = { version = "0.9", features = ["handlebars"] }
handlebars = { version = "5", features = ["dir_source"] }
serde.workspace = true
serde_json.workspace = true
