[package]
name = "middleware-rate-limit"
version = "1.0.0"
publish.workspace = true
edition.workspace = true

[dependencies]
actix-governor = "0.5"
actix-web.workspace = true
chrono.workspace = true
env_logger.workspace = true
futures-util.workspace = true
log.workspace = true
