[package]
name = "middleware-encrypted-payloads"
version = "1.0.0"
publish.workspace = true
edition.workspace = true

[dependencies]
actix-http.workspace = true
actix-web.workspace = true
aes-gcm-siv = "0.11"
base64 = "0.22"
env_logger.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
