[package]
name = "websocket-chat-actorless-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-files.workspace = true
actix-web.workspace = true
actix-ws.workspace = true
env_logger.workspace = true
futures-util.workspace = true
log.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["rt", "time", "macros"] }
