[package]
name = "json-validation"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web.workspace = true
awc = { workspace = true, features = ["openssl"] }

env_logger.workspace = true
futures-util.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
validator = { version = "0.18", features = ["derive"] }
